login-service-reps:
  login-service-representations:
    - hostname: api-service
      port: 8081
      login-resource-identifier: users
      client-id: api-service-client
    - hostname: dev-service
      port: 8083
      login-resource-identifier: developers
      client-id: dev-service-client